package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, remove the buildType with id = 'Build1130xyznc2o'
from your code, and delete the patch script.
*/
deleteBuildType(RelativeId("Build1130xyznc2o"))

