package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build2111'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build2111")) {
    expectSteps {
        script {
            scriptContent = "ping 127.0.0.1 -n 200 > nul"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            clearConditions()
            scriptContent = "ping 127.0.0.1 -n 2 > nul"
        }
    }
}
