package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build210xyz0ndp2o'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build210xyz0ndp2o")) {
    cleanup {
        add {
            baseRule {
                history(builds = 2)
            }
        }
    }
}
