package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.BuildType
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Subpr1_Gradle'
in the project with id = 'Subpr1', and delete the patch script.
*/
create(RelativeId("Subpr1"), BuildType({
    id("Subpr1_Gradle")
    name = "gradle"

    vcs {
        root(RelativeId("Subpr1_HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup"))
    }
}))

