package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.s3Storage
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            s3Storage {
                id = "PROJECT_EXT_52"
                bucketName = "n.chubatova-test"
                bucketPrefix = "a"
                awsEnvironment = default {
                    awsRegionName = "eu-central-1"
                }
                accessKeyID = "AKIA5JH2VERVHVMPJQJI"
                accessKey = "credentialsJSON:c7a2cd00-90f2-414a-876e-a5cb4bc3236d"
            }
        }
    }
}
