package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Subpr1_HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup'
in the project with id = 'Subpr1', and delete the patch script.
*/
create(RelativeId("Subpr1"), GitVcsRoot({
    id("Subpr1_HttpsGithubComChubatovaTigerChubatovaGradleTestsBackup")
    name = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
    url = "https://github.com/ChubatovaTiger/ChubatovaGradleTestsBackup"
    branch = "refs/heads/master"
}))

